### PR TITLE
Add rstheme_terminal_colors

### PR DESCRIPTION
**Pull request by nsgrantham**
Addresses #61. I implemented your recommended changes, the rainbow parens was a helpful example to follow, thank you. I tested this on my end and it's looking good. Let me know if there is something you'd like me to take a second pass at!

### CODE REVIEW

**Comment by nsgrantham** [comment]
Before:
Screen Shot 2021-03-30 at 11 39 58 PM

After:
Screen Shot 2021-03-30 at 11 38 35 PM

Here's the code where I use `rstheme_terminal_colors`: [https://github.com/nsgrantham/poolside-rstudio/blob/main/poolside.R](https://github.com/nsgrantham/poolside-rstudio/blob/main/poolside.R)

**Comment by nsgrantham** [comment]
Thanks, added my username to the NEWS item.

Glad you like Poolside! I'd love to add it to rsthemes, I'll open a PR when I'm done fiddling with it.

I don't entirely understand the `_terminal.scss` issue — does this mean the base themes need to be modified to use `rstheme_terminal_colors()` otherwise the partial is included twice?

**Comment by gadenbuie** [comment]
Thanks @nsgrantham and don't worry, I'll handle the `_terminal.scss` issue

**Comment by gadenbuie** [comment]
@nsgrantham sorry for the delay on this and thanks again for contributing the PR!

I tweaked the function signature and default arguments a bit. `rstheme_terminal_colors()` now picks up the theme's foreground and background colors and uses them for white and black. I also configured the args so that the `_bright` colors inherit from their non-bright colors, which makes it easier when you don't have a bright shade.

I also went through and added terminal colors to most themes in rsthemes, which is exciting!

**Pull request merged**
